codecov:
  disable_default_path_fixes: true

fixes:
  - "/home/scriticaluser/repos/::"
  - "**/site-packages/::"

coverage:
  status:
    project:
      default:
        threshold: 5%
    patch:
      default:
        target: 50%
