name: Docker setup

description: Shared steps to prepare repo environment and start container.

inputs:
  SCRITICAL_HOMEDIR:
    description: Base home directory for container paths
    required: false
    default: /home/scriticaluser
  BASHRC:
    description: Path to bashrc for container environment
    required: false
    default: /home/scriticaluser/.bashrc_scritical
  DOCKER_TAG:
    description: Docker image tag to use
    required: true
  BW_ACCESS_TOKEN:
    description: Bitwarden machine account access token
    required: true

runs:
  using: composite
  steps:
    - name: Set repo environment variables
      shell: bash
      run: |
        scritical_homedir="${{ inputs.SCRITICAL_HOMEDIR }}"
        echo "SCRITICAL_HOMEDIR=$scritical_homedir" >> "$GITHUB_ENV"
        echo "BASHRC=${{ inputs.BASHRC }}" >> "$GITHUB_ENV"
        repo_name="${{ github.event.repository.name }}"
        echo "REPO_NAME=$repo_name" >> "$GITHUB_ENV"
        echo "DOCKER_WORKING_DIR=$scritical_homedir/repos/$repo_name" >> "$GITHUB_ENV"
        echo "DOCKER_MOUNT_DIR=$scritical_homedir/mount/$repo_name" >> "$GITHUB_ENV"

    - name: Get Docker credentials from Bitwarden
      uses: bitwarden/sm-action@v2
      with:
        access_token: ${{ inputs.BW_ACCESS_TOKEN }}
        secrets: |
          71828b4d-6441-4e7d-b7f5-b3f8002289a5 > DOCKER_USERNAME
          e172281c-7428-412c-a86c-b3f7010f81bd > DOCKER_OAT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_OAT }}

    - name: Start Docker container
      shell: bash
      run: |
        docker run -t -d --name app \
          --mount "type=bind,src=${{ github.workspace }},target=${{ env.DOCKER_MOUNT_DIR }}" \
          scritical/private-dev:${{ inputs.DOCKER_TAG }} /bin/bash

        # Copy repo to working directory
        docker exec app /bin/bash -c "rm -rf $DOCKER_WORKING_DIR && mkdir -p $DOCKER_WORKING_DIR && cp -a $DOCKER_MOUNT_DIR/. $DOCKER_WORKING_DIR/"

