name: Docker setup

description: Shared steps to prepare repo environment and start container.

inputs:
  SCRITICAL_HOMEDIR:
    description: Base home directory for container paths
    required: false
    default: /home/scriticaluser
  BASHRC:
    description: Path to bashrc for container environment
    required: false
    default: /home/scriticaluser/.bashrc_scritical
  DOCKER_USER:
    description: Docker registry username
    required: true
  DOCKER_OAT:
    description: Docker registry Organization Access Token
    required: true
  DOCKER_TAG:
    description: Docker image tag to use
    required: true

runs:
  using: composite
  steps:
    - name: Set repo environment variables
      shell: bash
      run: |
        echo "SCRITICAL_HOMEDIR=${{ inputs.SCRITICAL_HOMEDIR }}" >> "$GITHUB_ENV"
        echo "BASHRC=${{ inputs.BASHRC }}" >> "$GITHUB_ENV"
        repo_name="${{ github.event.repository.name }}"
        echo "REPO_NAME=$repo_name" >> "$GITHUB_ENV"
        echo "DOCKER_WORKING_DIR=${{ env.SCRITICAL_HOMEDIR }}/repos/$repo_name" >> "$GITHUB_ENV"
        echo "DOCKER_MOUNT_DIR=${{ env.SCRITICAL_HOMEDIR }}/mount/$repo_name" >> "$GITHUB_ENV"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.DOCKER_USER }}
        password: ${{ inputs.DOCKER_OAT }}

    - name: Start Docker container
      shell: bash
      run: |
        docker run -t -d --name app \
          --mount "type=bind,src=${{ github.workspace }},target=${{ env.DOCKER_MOUNT_DIR }}" \
          scritical/private-dev:${{ inputs.DOCKER_TAG }} /bin/bash

        # Copy repo to working directory
        docker exec app /bin/bash -c "rm -rf $DOCKER_WORKING_DIR && mkdir -p $DOCKER_WORKING_DIR && cp -a $DOCKER_MOUNT_DIR/. $DOCKER_WORKING_DIR/"

